# Generated by Django 4.0.4 on 2022-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeBoard', '0003_massmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmail',
            name='text',
            field=models.TextField(),
        ),
    ]